name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_NAME: test_db
      DATABASE_USER: test_user
      DATABASE_PASSWORD: test_password
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      DJANGO_SETTINGS_MODULE: messaging_app.settings
      PYTHONPATH: ${{ github.workspace }}/messaging_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./messaging_app
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL to be ready
        run: |
          sudo apt-get install -y mysql-client
          until mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; do
            echo "Waiting for database connection..."
            sleep 5
          done

      - name: Apply database migrations
        working-directory: ./messaging_app
        run: |
          python manage.py migrate

      - name: Run Django tests
        working-directory: ./messaging_app
        run: |
          pytest --ds=messaging_app.settings --junitxml=test-results.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: django-test-results
          path: messaging_app/test-results.xml
